services:

  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  # TODO: IMPLEMENT REPLICAS

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
      - ./dbs/mysql:/backup

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql

  php:
    image: php:8.3-apache
    container_name: php
    ports:
      - "8000:80"
    volumes:
      - ./php:/var/www/html
    depends_on:
      - mysql

volumes:
  mongo_data:
  mysql_data:
