# Temperature Thresholds
TEMP_THRESHOLD = 40.0
TEMP_ANTI_SPAM_SECONDS = 60

# Sound Outlier Variables
SOUND_RATIO_MAX = 50.0
SOUND_RATIO_MIN = 0.01
SOUND_DELTA_MOVEMENT_MAX = 1
SOUND_DELTA_SOUND_THRESHOLD = 30.0
SOUND_ABS_DIFF_THRESHOLD = 50.0
SOUND_MOVEMENT_WINDOW_SECONDS = 10

# Actuator Thresholds
ACTUATOR_TEMP_HIGH = 50.0
ACTUATOR_TEMP_LOW = 10.0
ACTUATOR_SOUND_HIGH = 100.0
ACTUATOR_TOPIC = "pisid_mazeact"
