# Temperature Thresholds
TEMP_THRESHOLD = 40.0
TEMP_ANTI_SPAM_SECONDS = 60

# Sound Outlier Variables
SOUND_RATIO_MAX = 3.0
SOUND_RATIO_MIN = 0.1
SOUND_DELTA_MOVEMENT_MAX = 1
SOUND_DELTA_SOUND_THRESHOLD = 5.0
SOUND_ABS_DIFF_THRESHOLD = 10.0
SOUND_MOVEMENT_WINDOW_SECONDS = 10
