services:
  # Nó Principal
  mongo-db:
    image: mongo:7
    container_name: mazerun-mongo-db
    ports:
      - "27017:27017"
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongo_data_1:/data/db

  # Nó Secundário 1
  mongo-replica-1:
    image: mongo:7
    container_name: mazerun-mongo-replica-1
    ports:
      - "27018:27017"
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongo_data_2:/data/db

  # Nó Secundário 2
  mongo-replica-2:
    image: mongo:7
    container_name: mazerun-mongo-replica-2
    ports:
      - "27019:27017"
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongo_data_3:/data/db

  # Serviço de Setup (corre uma vez para configurar o cluster)
  mongo-setup:
    image: mongo:7
    container_name: mazerun-mongo-setup
    depends_on:
      - mongo-db
      - mongo-replica-1
      - mongo-replica-2
    entrypoint: >
      bash -c "
        echo 'Waiting for nodes...' &&
        sleep 10 &&
        mongosh --host mongo-db:27017 --eval '
          try {
            rs.initiate({
              _id: \"rs0\",
              members: [
                {_id: 0, host: \"mongo-db:27017\", priority: 2},
                {_id: 1, host: \"mongo-replica-1:27017\", priority: 1},
                {_id: 2, host: \"mongo-replica-2:27017\", priority: 1}
              ]
            });
            print(\"Replica Set initialized!\");
          } catch(e) {
            print(\"Already initialized or error: \" + e.message);
          }
        '
      "

  # A nossa Aplicação Python
  mongo-app:
    build: .
    container_name: mazerun-mongo-app
    depends_on:
      - mongo-db
    volumes:
      - ./config.yaml:/app/config.yaml
    environment:
      # URI atualizada para incluir o Replica Set
      - MONGO_URI=mongodb://mongo-db:27017,mongo-replica-1:27017,mongo-replica-2:27017/?replicaSet=rs0

volumes:
  mongo_data_1:
  mongo_data_2:
  mongo_data_3:
